{{- if and (eq .Values.opencloud.storage.mode "s3") .Values.opencloud.storage.s3.enabled (and .Values.opencloud.storage.s3.persistence.enabled (not .Values.opencloud.storage.s3.persistence.existingClaim)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencloud.minio.fullname" . }}-data
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  accessModes:
    - {{ .Values.opencloud.storage.s3.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.opencloud.storage.s3.persistence.size | quote }}
  {{- if .Values.opencloud.storage.s3.persistence.storageClass }}
  {{- if (eq "-" .Values.opencloud.storage.s3.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.opencloud.storage.s3.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
