{{- if and .Values.ingress.enabled .Values.oidc.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opencloud.fullname" . }}-keycloak
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.global.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.domain.oidc | quote }}
      {{- if not (empty .Values.global.tls.secretName) }}
      secretName: {{ .Values.global.tls.secretName }}-keycloak
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.global.domain.oidc | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "opencloud.keycloak.fullname" . }}
                port:
                  number: 8080
{{- end }}
