{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.keycloak.fullname" . }}-realm
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
data:
  openCloud-realm.json: |-
{{ tpl (.Files.Get "files/keycloak/openCloud-realm.json.gotmpl") .  | indent 4 }}
{{- end }}
